<?

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$nameStr = ($block->getNameInLayout());
$nameStrArr = explode(".", $nameStr);
$name = $nameStrArr[2];
$url = $this->helper('Vahov\SystemConfigurationsSocials\Helper\Data')->getSystemConfig($name);

?>

<li class="socials__item">
    <a class="socials__link" aria-label="<?= $name; ?>" href='<?= $url; ?>' target="_blank">
        <i class="socials__icon zmdi zmdi-<?= $name; ?>"></i>
    </a>
</li>