<?

use Magento\Framework\View\Element\Template;

/** @var Template $block */

$name = ($block->getNameInLayout());

$imgUrl = $block->getData("icon_${name}");
$title = $block->getData("title_${name}");
$text = $block->getData("text_${name}");

?>

<div class="feature__box">
  <img class="feature__icon" src="<?= $block->getViewFileUrl('Magento_Theme::' . $imgUrl); ?>" alt="<?= $name; ?>" />
  <div class="feature__description">
    <h4 class="feature__title"><?= $title; ?></h4>
    <p class="feature__text"><?= $text; ?></p>
  </div>
</div>