<?

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>

<div class="hero__slider slider">
  <div class="slider__line">
    <img class="slider__img" src="<?= $block->getViewFileUrl('Magento_Theme::images/backgrounds/hero-girl-1.png'); ?>" alt="girl-1" />
    <img class="slider__img" src="<?= $block->getViewFileUrl('Magento_Theme::images/backgrounds/hero-girl-2.png'); ?>" alt="girl-2" />
    <img class="slider__img" src="<?= $block->getViewFileUrl('Magento_Theme::images/backgrounds/hero-girl-3.png'); ?>" alt="girl-3" />
    <img class="slider__img" src="<?= $block->getViewFileUrl('Magento_Theme::images/backgrounds/hero-boy-1.png'); ?>" alt="boy-1" />
  </div>
</div>